const genshinDatabase = [
  { name: "丝柯克", img: "", region: "纳塔", star: "五星", vision: "未知", element: "冰", weapon: "单手剑", special: "" },
  { name: "爱可菲", img: "", region: "枫丹廷", star: "五星", vision: "枫丹", element: "冰", weapon: "长柄武器", special: "始基力 荒" },
  { name: "塔利雅", img: "", region: "蒙德城", star: "四星", vision: "蒙德", element: "水", weapon: "单手剑", special: "" },
  { name: "坎蒂丝", img: "https://genshin.jmp.blue/characters/candace/icon-big.png", region: "须弥城", star: "四星", vision: "须弥", element: "水", weapon: "长柄武器", special: "" },
  { name: "夏洛蒂", img: "https://genshin.jmp.blue/characters/charlotte/icon-big.png", region: "枫丹廷", star: "四星", vision: "枫丹", element: "冰", weapon: "法器", special: "始基力 芒" },
  { name: "法尔伽", img: "", region: "蒙德城", star: "五星", vision: "蒙德", element: "风", weapon: "双手剑", special: "魔导" },
  { name: "菲林斯", img: "", region: "挪德卡莱", star: "五星", vision: "挪德卡莱", element: "雷", weapon: "长柄武器", special: "月兆" },
  { name: "优菈", img: "https://genshin.jmp.blue/characters/eula/icon-big.png", region: "蒙德城", star: "五星", vision: "蒙德", element: "冰", weapon: "双手剑", special: "" },
  { name: "莫娜", img: "https://genshin.jmp.blue/characters/mona/icon-big.png", region: "蒙德城", star: "五星", vision: "蒙德", element: "水", weapon: "法器", special: "魔导" },
  { name: "阿贝多", img: "https://genshin.jmp.blue/characters/albedo/icon-big.png", region: "蒙德城", star: "五星", vision: "蒙德", element: "岩", weapon: "单手剑", special: "魔导" },
  { name: "可莉", img: "https://genshin.jmp.blue/characters/klee/icon-big.png", region: "蒙德城", star: "五星", vision: "蒙德", element: "火", weapon: "法器", special: "魔导" },
  { name: "迪卢克", img: "https://genshin.jmp.blue/characters/diluc/icon-big.png", region: "蒙德城", star: "五星", vision: "蒙德", element: "火", weapon: "双手剑", special: "" },
  { name: "琴", img: "https://genshin.jmp.blue/characters/jean/icon-big.png", region: "蒙德城", star: "五星", vision: "蒙德", element: "风", weapon: "单手剑", special: "" },
  { name: "班尼特", img: "https://genshin.jmp.blue/characters/bennett/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "火", weapon: "单手剑", special: "" },
  { name: "香菱", img: "https://genshin.jmp.blue/characters/xiangling/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "火", weapon: "长柄武器", special: "" },
  { name: "砂糖", img: "https://genshin.jmp.blue/characters/sucrose/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "风", weapon: "法器", special: "魔导" },
  { name: "兹白", img: "", region: "璃月港", star: "五星", vision: "璃月", element: "岩", weapon: "单手剑", special: "月兆" },
  { name: "那维莱特", img: "https://genshin.jmp.blue/characters/neuvillette/icon-big.png", region: "枫丹廷", star: "五星", vision: "枫丹", element: "水", weapon: "法器", special: "始基力 芒" },
  { name: "叶洛亚", img: "", region: "挪德卡莱", star: "四星", vision: "挪德卡莱", element: "岩", weapon: "长柄武器", special: "月兆" },
  { name: "爱诺", img: "", region: "挪德卡莱", star: "四星", vision: "挪德卡莱", element: "水", weapon: "双手剑", special: "月兆" },
  { name: "五郎", img: "https://genshin.jmp.blue/characters/gorou/icon-big.png", region: "稻妻城", star: "四星", vision: "稻妻", element: "岩", weapon: "弓", special: "" },
  { name: "哥伦比娅", img: "", region: "挪德卡莱", star: "五星", vision: "挪德卡莱", element: "水", weapon: "法器", special: "月兆" },
  { name: "伊涅芙", img: "", region: "挪德卡莱", star: "五星", vision: "挪德卡莱", element: "雷", weapon: "长柄武器", special: "月兆" },
  { name: "伊法", img: "", region: "纳塔", star: "四星", vision: "纳塔", element: "风", weapon: "法器", special: "燃素" },
  { name: "菲谢尔", img: "https://genshin.jmp.blue/characters/fischl/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "雷", weapon: "弓", special: "魔导" },
  { name: "赛索斯", img: "https://genshin.jmp.blue/characters/sethos/icon-big.png", region: "须弥城", star: "四星", vision: "须弥", element: "雷", weapon: "弓", special: "" },
  { name: "杜林", img: "", region: "蒙德城", star: "五星", vision: "蒙德", element: "火", weapon: "单手剑", special: "魔导" },
  { name: "雅珂达", img: "", region: "挪德卡莱", star: "四星", vision: "挪德卡莱", element: "风", weapon: "弓", special: "月兆" },
  { name: "奈芙尔", img: "", region: "挪德卡莱", star: "五星", vision: "挪德卡莱", element: "草", weapon: "法器", special: "月兆" },
  { name: "奇偶·男性", img: "", region: "", star: "", vision: "", element: "", weapon: "单手剑", special: "" },
  { name: "奇偶·女性", img: "", region: "", star: "", vision: "", element: "", weapon: "单手剑", special: "" },
  { name: "芙宁娜", img: "https://genshin.jmp.blue/characters/furina/icon-big.png", region: "枫丹廷", star: "五星", vision: "枫丹", element: "水", weapon: "单手剑", special: "始基力 芒" },
  { name: "菈乌玛", img: "", region: "挪德卡莱", star: "五星", vision: "挪德卡莱", element: "草", weapon: "法器", special: "月兆" },
  { name: "纳西妲", img: "https://genshin.jmp.blue/characters/nahida/icon-big.png", region: "须弥城", star: "五星", vision: "须弥", element: "草", weapon: "法器", special: "" },
  { name: "妮露", img: "https://genshin.jmp.blue/characters/nilou/icon-big.png", region: "须弥城", star: "五星", vision: "须弥", element: "水", weapon: "单手剑", special: "" },
  { name: "艾尔海森", img: "https://genshin.jmp.blue/characters/alhaitham/icon-big.png", region: "须弥城", star: "五星", vision: "须弥", element: "草", weapon: "单手剑", special: "" },
  { name: "赛诺", img: "https://genshin.jmp.blue/characters/cyno/icon-big.png", region: "须弥城", star: "五星", vision: "须弥", element: "雷", weapon: "长柄武器", special: "" },
  { name: "流浪者", img: "https://genshin.jmp.blue/characters/wanderer/icon-big.png", region: "须弥城", star: "五星", vision: "须弥", element: "风", weapon: "法器", special: "" },
  { name: "提纳里", img: "https://genshin.jmp.blue/characters/tighnari/icon-big.png", region: "须弥城", star: "五星", vision: "须弥", element: "草", weapon: "弓", special: "" },
  { name: "迪希雅", img: "https://genshin.jmp.blue/characters/dehya/icon-big.png", region: "须弥城", star: "五星", vision: "须弥", element: "火", weapon: "双手剑", special: "" },
  { name: "恰斯卡", img: "https://genshin.jmp.blue/characters/chasca/icon-big.png", region: "纳塔", star: "五星", vision: "纳塔", element: "风", weapon: "弓", special: "燃素" },
  { name: "玛拉妮", img: "https://genshin.jmp.blue/characters/mualani/icon-big.png", region: "纳塔", star: "五星", vision: "纳塔", element: "水", weapon: "法器", special: "燃素" },
  { name: "欧洛伦", img: "https://genshin.jmp.blue/characters/ororon/icon-big.png", region: "纳塔", star: "四星", vision: "纳塔", element: "雷", weapon: "弓", special: "燃素" },
  { name: "茜特菈莉", img: "https://genshin.jmp.blue/characters/citlali/icon-big.png", region: "纳塔", star: "五星", vision: "纳塔", element: "冰", weapon: "法器", special: "燃素" },
  { name: "行秋", img: "https://genshin.jmp.blue/characters/xingqiu/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "水", weapon: "单手剑", special: "" },
  { name: "玛薇卡", img: "https://genshin.jmp.blue/characters/mavuika/icon-big.png", region: "纳塔", star: "五星", vision: "纳塔", element: "火", weapon: "双手剑", special: "燃素" },
  { name: "艾梅莉埃", img: "https://genshin.jmp.blue/characters/emilie/icon-big.png", region: "枫丹廷", star: "五星", vision: "枫丹", element: "草", weapon: "长柄武器", special: "始基力 芒" },
  { name: "伊安珊", img: "https://genshin.jmp.blue/characters/iansan/icon-big.png", region: "纳塔", star: "四星", vision: "纳塔", element: "火", weapon: "长柄武器", special: "燃素" },
  { name: "瑶瑶", img: "https://genshin.jmp.blue/characters/yaoyao/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "草", weapon: "长柄武器", special: "" },
  { name: "申鹤", img: "https://genshin.jmp.blue/characters/shenhe/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "冰", weapon: "长柄武器", special: "" },
  { name: "迪奥娜", img: "https://genshin.jmp.blue/characters/diona/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "冰", weapon: "弓", special: "" },
  { name: "基尼奇", img: "https://genshin.jmp.blue/characters/kinich/icon-big.png", region: "纳塔", star: "五星", vision: "纳塔", element: "草", weapon: "双手剑", special: "燃素" },
  { name: "雷电将军", img: "https://genshin.jmp.blue/characters/raiden/icon-big.png", region: "稻妻城", star: "五星", vision: "稻妻", element: "雷", weapon: "长柄武器", special: "" },
  { name: "神里绫华", img: "https://genshin.jmp.blue/characters/ayaka/icon-big.png", region: "稻妻城", star: "五星", vision: "稻妻", element: "冰", weapon: "单手剑", special: "" },
  { name: "神里绫人", img: "https://genshin.jmp.blue/characters/ayato/icon-big.png", region: "稻妻城", star: "五星", vision: "稻妻", element: "水", weapon: "单手剑", special: "" },
  { name: "珐露珊", img: "https://genshin.jmp.blue/characters/faruzan/icon-big.png", region: "须弥城", star: "四星", vision: "须弥", element: "风", weapon: "弓", special: "" },
  { name: "千织", img: "https://genshin.jmp.blue/characters/chiori/icon-big.png", region: "稻妻城", star: "五星", vision: "稻妻", element: "岩", weapon: "单手剑", special: "" },
  { name: "八重神子", img: "https://genshin.jmp.blue/characters/yae-miko/icon-big.png", region: "稻妻城", star: "五星", vision: "稻妻", element: "雷", weapon: "法器", special: "" },
  { name: "荒泷一斗", img: "https://genshin.jmp.blue/characters/arataki-itto/icon-big.png", region: "稻妻城", star: "五星", vision: "稻妻", element: "岩", weapon: "双手剑", special: "" },
  { name: "宵宫", img: "https://genshin.jmp.blue/characters/yoimiya/icon-big.png", region: "稻妻城", star: "五星", vision: "稻妻", element: "火", weapon: "弓", special: "" },
  { name: "琳妮特", img: "https://genshin.jmp.blue/characters/lynette/icon-big.png", region: "枫丹廷", star: "四星", vision: "枫丹", element: "风", weapon: "单手剑", special: "始基力 荒" },
  { name: "九条裟罗", img: "https://genshin.jmp.blue/characters/sara/icon-big.png", region: "稻妻城", star: "四星", vision: "稻妻", element: "雷", weapon: "弓", special: "" },
  { name: "托马", img: "https://genshin.jmp.blue/characters/thoma/icon-big.png", region: "稻妻城", star: "四星", vision: "稻妻", element: "火", weapon: "长柄武器", special: "" },
  { name: "娜维娅", img: "https://genshin.jmp.blue/characters/navia/icon-big.png", region: "枫丹廷", star: "五星", vision: "枫丹", element: "岩", weapon: "双手剑", special: "始基力 荒" },
  { name: "莱依拉", img: "https://genshin.jmp.blue/characters/layla/icon-big.png", region: "须弥城", star: "四星", vision: "须弥", element: "冰", weapon: "单手剑", special: "" },
  { name: "希诺宁", img: "https://genshin.jmp.blue/characters/xilonen/icon-big.png", region: "纳塔", star: "五星", vision: "纳塔", element: "岩", weapon: "单手剑", special: "燃素" },
  { name: "温迪", img: "https://genshin.jmp.blue/characters/venti/icon-big.png", region: "蒙德城", star: "五星", vision: "蒙德", element: "风", weapon: "弓", special: "魔导" },
  { name: "烟绯", img: "https://genshin.jmp.blue/characters/yanfei/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "火", weapon: "法器", special: "" },
  { name: "闲云", img: "https://genshin.jmp.blue/characters/xianyun/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "风", weapon: "法器", special: "" },
  { name: "北斗", img: "https://genshin.jmp.blue/characters/beidou/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "雷", weapon: "双手剑", special: "" },
  { name: "瓦雷莎", img: "https://genshin.jmp.blue/characters/varesa/icon-big.png", region: "纳塔", star: "五星", vision: "纳塔", element: "冰", weapon: "长柄武器", special: "燃素" },
  { name: "夏沃蕾", img: "https://genshin.jmp.blue/characters/chevreuse/icon-big.png", region: "枫丹廷", star: "四星", vision: "枫丹", element: "火", weapon: "长柄武器", special: "始基力 荒" },
  { name: "嘉明", img: "https://genshin.jmp.blue/characters/gaming/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "火", weapon: "双手剑", special: "" },
  { name: "希格雯", img: "https://genshin.jmp.blue/characters/sigewinne/icon-big.png", region: "枫丹廷", star: "五星", vision: "枫丹", element: "水", weapon: "弓", special: "始基力 芒" },
  { name: "莱欧斯利", img: "https://genshin.jmp.blue/characters/wriothesley/icon-big.png", region: "枫丹廷", star: "五星", vision: "枫丹", element: "冰", weapon: "法器", special: "始基力 荒" },
  { name: "蓝砚", img: "https://genshin.jmp.blue/characters/lan-yan/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "水", weapon: "法器", special: "" },
  { name: "梦见月瑞希", img: "https://genshin.jmp.blue/characters/yumemizuki-mizuki/icon-big.png", region: "稻妻城", star: "四星", vision: "稻妻", element: "风", weapon: "法器", special: "" },
  { name: "阿蕾奇诺", img: "https://genshin.jmp.blue/characters/arlecchino/icon-big.png", region: "枫丹廷", star: "五星", vision: "愚人众", element: "火", weapon: "长柄武器", special: "始基力 荒" },
  { name: "克洛琳德", img: "https://genshin.jmp.blue/characters/clorinde/icon-big.png", region: "枫丹廷", star: "五星", vision: "枫丹", element: "雷", weapon: "单手剑", special: "始基力 芒" },
  { name: "白术", img: "https://genshin.jmp.blue/characters/baizhu/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "草", weapon: "法器", special: "" },
  { name: "刻晴", img: "https://genshin.jmp.blue/characters/keqing/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "雷", weapon: "单手剑", special: "" },
  { name: "甘雨", img: "https://genshin.jmp.blue/characters/ganyu/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "冰", weapon: "弓", special: "" },
  { name: "七七", img: "https://genshin.jmp.blue/characters/qiqi/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "冰", weapon: "单手剑", special: "" },
  { name: "魈", img: "https://genshin.jmp.blue/characters/xiao/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "风", weapon: "长柄武器", special: "" },
  { name: "达达利亚", img: "https://genshin.jmp.blue/characters/tartaglia/icon-big.png", region: "璃月港", star: "五星", vision: "愚人众", element: "水", weapon: "弓", special: "" },
  { name: "钟离", img: "https://genshin.jmp.blue/characters/zhongli/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "岩", weapon: "长柄武器", special: "" },
  { name: "胡桃", img: "https://genshin.jmp.blue/characters/hu-tao/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "火", weapon: "长柄武器", special: "" },
  { name: "卡齐娜", img: "https://genshin.jmp.blue/characters/kachina/icon-big.png", region: "纳塔", star: "四星", vision: "纳塔", element: "岩", weapon: "双手剑", special: "燃素" },
  { name: "枫原万叶", img: "https://genshin.jmp.blue/characters/kazuha/icon-big.png", region: "稻妻城", star: "五星", vision: "稻妻", element: "风", weapon: "单手剑", special: "" },
  { name: "夜兰", img: "https://genshin.jmp.blue/characters/yelan/icon-big.png", region: "璃月港", star: "五星", vision: "璃月", element: "水", weapon: "弓", special: "" },
  { name: "林尼", img: "https://genshin.jmp.blue/characters/lyney/icon-big.png", region: "枫丹廷", star: "五星", vision: "枫丹", element: "火", weapon: "弓", special: "始基力 芒" },
  { name: "珊瑚宫心海", img: "https://genshin.jmp.blue/characters/kokomi/icon-big.png", region: "稻妻城", star: "五星", vision: "稻妻", element: "水", weapon: "法器", special: "" },
  { name: "诺艾尔", img: "https://genshin.jmp.blue/characters/noelle/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "岩", weapon: "双手剑", special: "" },
  { name: "菲米尼", img: "https://genshin.jmp.blue/characters/freminet/icon-big.png", region: "枫丹廷", star: "四星", vision: "枫丹", element: "冰", weapon: "双手剑", special: "始基力 荒" },
  { name: "罗莎莉亚", img: "https://genshin.jmp.blue/characters/rosaria/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "冰", weapon: "长柄武器", special: "" },
  { name: "绮良良", img: "https://genshin.jmp.blue/characters/kirara/icon-big.png", region: "稻妻城", star: "四星", vision: "稻妻", element: "草", weapon: "单手剑", special: "" },
  { name: "卡维", img: "https://genshin.jmp.blue/characters/kaveh/icon-big.png", region: "须弥城", star: "四星", vision: "须弥", element: "草", weapon: "双手剑", special: "" },
  { name: "米卡", img: "https://genshin.jmp.blue/characters/mika/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "冰", weapon: "长柄武器", special: "" },
  { name: "多莉", img: "https://genshin.jmp.blue/characters/dori/icon-big.png", region: "须弥城", star: "四星", vision: "须弥", element: "雷", weapon: "双手剑", special: "" },
  { name: "柯莱", img: "https://genshin.jmp.blue/characters/collei/icon-big.png", region: "须弥城", star: "四星", vision: "须弥", element: "草", weapon: "弓", special: "" },
  { name: "鹿野院平藏", img: "https://genshin.jmp.blue/characters/shikanoin-heizou/icon-big.png", region: "稻妻城", star: "四星", vision: "稻妻", element: "风", weapon: "法器", special: "" },
  { name: "云堇", img: "https://genshin.jmp.blue/characters/yun-jin/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "岩", weapon: "长柄武器", special: "" },
  { name: "凝光", img: "https://genshin.jmp.blue/characters/ningguang/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "岩", weapon: "法器", special: "" },
  { name: "久岐忍", img: "https://genshin.jmp.blue/characters/kuki-shinobu/icon-big.png", region: "稻妻城", star: "四星", vision: "稻妻", element: "雷", weapon: "单手剑", special: "" },
  { name: "早柚", img: "https://genshin.jmp.blue/characters/sayu/icon-big.png", region: "稻妻城", star: "四星", vision: "稻妻", element: "风", weapon: "双手剑", special: "" },
  { name: "重云", img: "https://genshin.jmp.blue/characters/chongyun/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "冰", weapon: "双手剑", special: "" },
  { name: "丽莎", img: "https://genshin.jmp.blue/characters/lisa/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "雷", weapon: "法器", special: "魔导" },
  { name: "辛焱", img: "https://genshin.jmp.blue/characters/xinyan/icon-big.png", region: "璃月港", star: "四星", vision: "璃月", element: "火", weapon: "双手剑", special: "" },
  { name: "雷泽", img: "https://genshin.jmp.blue/characters/razor/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "雷", weapon: "双手剑", special: "" },
  { name: "凯亚", img: "https://genshin.jmp.blue/characters/kaeya/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "冰", weapon: "单手剑", special: "" },
  { name: "芭芭拉", img: "https://genshin.jmp.blue/characters/barbara/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "水", weapon: "法器", special: "" },
  { name: "安柏", img: "https://genshin.jmp.blue/characters/amber/icon-big.png", region: "蒙德城", star: "四星", vision: "蒙德", element: "火", weapon: "弓", special: "" },
  { name: "埃洛伊", img: "https://genshin.jmp.blue/characters/aloy/icon-big.png", region: "未知", star: "", vision: "未知", element: "冰", weapon: "弓", special: "" },
  { name: "旅行者·火", img: "", region: "纳塔", star: "", vision: "", element: "火", weapon: "单手剑", special: "" },
  { name: "旅行者·水", img: "", region: "枫丹廷", star: "", vision: "", element: "水", weapon: "单手剑", special: "" },
  { name: "旅行者·草", img: "", region: "须弥城", star: "", vision: "", element: "草", weapon: "单手剑", special: "" },
  { name: "旅行者·雷", img: "", region: "稻妻城", star: "", vision: "", element: "雷", weapon: "单手剑", special: "" },
  { name: "旅行者·岩", img: "", region: "璃月港", star: "", vision: "", element: "岩", weapon: "单手剑", special: "" },
  { name: "旅行者·风", img: "", region: "蒙德城", star: "", vision: "", element: "风", weapon: "单手剑", special: "" }
];
